default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: chat_app_development
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  host: db
  database: chat_app_test
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: chat_app_production
