version: "3.9"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    ports:
    - 3306:3306
  api:
    build: ./backend/.
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend/.
    command: ash -c "yarn dev"
    ports: 
      - 3030:3030
    volumes:
      - ./frontend:/frontend
    depends_on:
      - api
    expose:
      - 3030
