---
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1
  DisplayCopNames: true
  Exclude:
    - /**/bin/**/*
    - /**/db/**/*
    - /**/vendor/**/*

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Style/TernaryParentheses:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  AllowHeredoc: true

Metrics/MethodLength:
  Max: 30


RSpec/MultipleExpectations:
  Enabled: false
